--EASY PROBLEM--

use subqueries
CREATE TABLE EMP(
EMP_ID INT
)
INSERT INTO EMP (EMP_ID) 
VALUES (2), (4), (4), (6), (6), (7), (8), (8);

--SELECT *FROM EMP;


SELECT MAX(EMP_ID)  AS  [single_heghest]FROM EMP 
WHERE EMP_ID NOT IN(
SELECT EMP_ID FROM EMP
GROUP BY EMP_ID
HAVING COUNT(EMP_ID)>1)
